### ISSUE TITLE
PS to #62

### ISSUE THREAD

**Issue by real-yfprojects** [asottile/blacken-docs#182]
I think restricting commenting on #62 to collaborators is not an appropriate reaction. My first comment wanted to help, my second expressed my motivation. Locking the thread after that appears like the reaction of somebody not able to cope with minor criticism.

Why am I writing this? Actually I only wanted to add the following comment probably being very relevant in the future of #62:
***
I just found this issue psf/black#779 that tracks the progress on making a public API available for black that includes 

> A function for executing Black with its whole configuration discovery and file manipulation

**Comment by asottile** [comment]
I locked it because you dug up a 2 year old thread with a poor suggested solution which doesn't address the technical limitations and then when told no followed up with a lowball complaint.  I do not intend to continue the conversation.

if you wanted to add that comment you should have done it in your first message
